// Handle exceptions using try...catch.

try{
    const a = 0/0;
    console.log(a);
} catch(error){
    console.error("Error");
}